from telethon import TelegramClient, sync, events
from telethon.tl.functions.messages import GetHistoryRequest, GetBotCallbackAnswerRequest
from telethon.tl.functions.channels import JoinChannelRequest
from telethon.errors import SessionPasswordNeededError
from telethon.errors import FloodWaitError
from time import sleep, time
from colorama import Fore,Style, init as color_ama
color_ama(autoreset=True)
import json, re, sys, os, random

banner = Style.BRIGHT+Fore.YELLOW +  """

   ____               _   
  / ___| ___ __ _ ___| |_ 
 | |  _ / __/ _` / __| __|
 | |_| | (_| (_| \__ \ |_ 
  \____|\___\__,_|___/\__|
                          
  Creator : MK KHAIRIL || Youtube : MK KHAIRIL
  Support : Cocentz404 || Youtube : Cocentz404"""

putih = Style.BRIGHT+Fore.WHITE
hijau = Style.BRIGHT+Fore.GREEN
merah = Style.BRIGHT+Fore.RED
kuning = Style.BRIGHT+Fore.YELLOW
reset = Fore.RESET
biru = Style.BRIGHT+Fore.BLUE


os.system('clear') 
print(banner)
print("\n")
print(f'{hijau}[+] Indonesia/English')
import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
#kecepatan mengetik
        time.sleep(random.random() * 0.2)
#ubah angka 0.1 sesuai keinginan kamu
#angka terkecil adalah yang paling cepat
#angka terbesar adalah yang paling lambat
mengetik("[+] Ini Adalah Program Ilegal\n[+] Semua Resiko Harap Ditanggung Pengguna..!!\n[+] This Is An Illegal Program\n[+] All Risks Borne by Users...!\n")
if not os.path.exists('session'):
    os.makedirs('session')
if len(sys.argv) < 2:
    print( Fore.RED + '\n\nUsage : python main.py +62' + Fore.RESET)
    sys.exit(1)
api_id = 1148490
api_hash = 'd82c81323285aeb9c2ba9ee420d8b009'
phone_number = sys.argv[1]
client = TelegramClient('session/' + phone_number, api_id, api_hash)
client.connect()
if not client.is_user_authorized():
    try:
        client.send_code_request(phone_number)
        me = client.sign_in(phone_number, input(Fore.WHITE + 'Enter Yout Code Code : '))
    except SessionPasswordNeededError:
        passw = input(Fore.RESET + 'Your 2fa Password : ')
        me = client.start(phone_number, passw)
saia = client.get_me()
print('[*]Account:',saia.first_name)
print('[*]Phone:',saia.phone,'\n')
channel_username = '@gcastod'
channel_entity = client.get_entity('@gcastod')
print('Memulai Bot Gcast..!')


while True:
  try:
    client.send_message(entity=channel_entity, message='.bc group jgn manja deh mls aku nya hwehehe')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)    
    client.send_message(entity=channel_entity, message='.bc group wiwikw')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300) 
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group ohh disini ya sibuk ya hmmm')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group mami dsini mantau yaa')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group mandhii yukk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group aqkaquuuuu omexxxx dibyoooughh^')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group sini dong hwehehee')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group rate mami dongggd')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group paddaa oummeeeckkj ihhhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group chooliii pake balsem seruuu dhhiii biiooyooo0')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group -1 ayangggg nihh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1Qu1FFULL OSMECSCCKSS DESAHHH DIYY BIYYOOOUHH1HH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1BATLEEE  OMEKCKK VS BATLEEE COLY DI BIUHHHHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^11QWUD4AHHHHHH D1MUULAIIIII BURU4NNNNNN CEKKKKKK B1000KKKKKKKCKKK1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1TIEEEEMMEEEININNN AKKKUUU SAINGGGEEEEKK DDDEEEBEEE11O')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1MEM31MMMLMKS TEMBEM DIIBYIIOOU AK SAYANGGGGF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1QWL1IVFEEE NNGEUWEEE UDAAHHH MULAIIII DI BIYO0OOOU BURU JOINNNN1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^11QWTIEEEMMMMEEEININN AKKKUUU SAINGDGGE3EEEKK DDDEEEBEEEOI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1SOKK1NN TM0 C`UANN DIBYIOUHHH1HH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1ANA4K `SMMA NGEU33 SAMA OM` DI BBHHEYOKKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QWS1SSIIAAIAR.RAAA`N LANGSUNG PER0MEEEKAAANN DIB;1Y000HHHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW^1LLI`STINIIIi.IERR KIAA OMEXKCG BAWBRBWRR DBYOHGHHHFF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW^11OOOUH`HMEX PINKK.KK FULL DESAAG BANNGGEET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW^11AQKU ANGG`HEE.KKKK PARAHHHHDI BYUIOHHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW^1C1CH``OLLL`ME.E3KKKKKKINNNN BBBBHHHIIIYYUUUUHHHUK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW^1`1CCHHOL.LLL MEEEKKKKINNNN BHH`HYIIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^11NHN-G.UEEWEEE BBRU`TALLL BGTTT DI BIYOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW^1`1CHOLLLLLMEEFEKKMK`INNNN BHIHHYIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1`1`MMMA`4MMIIII OOE.MM`EEEXXCKK BBBHYIIIOOUKKIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^11OO.OHHHHME.EECXK.KIN`NN MOMMMIIIIIKUI BHHHHIIIIOOOYOOOOK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^11MMAAA4AMMIIII OOEM`MMEEEXXCKK BBBHYIIIOOUKKIIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^11SSSIIAAIAJRAAAN LANG`ASUNG PER0MEEEKAAANN DIB;1Y000HHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11CHEAAKK DI PLHJAOP`JIL AKU ADA YANHG LAGI ENHAK ENSHAK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11OOUHHMEX PIJNKA`KK FULL DESAAG BANNGGET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11AKUUUOUU COOLLLME`AJEEKKK BHYYYEIOOOOIOOKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^11SIII AALEEAAA AANG`EEJEEE BBHYYYYYTOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group QW^1S1SIARAAAN LAANGISAU`NG PPER0MEEKAAANN DIB;1Y000HHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group QW^11CCEK DI PLIHOPJIL A`KU AAADA YAANG LAGI ENHAK ENHAK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1NNN1ONTON 0VMEJECKAK`K YUKKKK DIB¡1.Y000HH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^112WOI ANJRIT, NGHEHWAE`NYA BWARBWAR BGT DIBHIOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1M1ALLLEEMMHMM IAINN`NI PPAAARTTYYY NGGGGEEIWEEEEEE DEEBBBBBIIOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11NNGGGEEWEHEEE BBBR`AUUTTA4ALL BANGGETT DDIIBBEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^11ADHA YGAAN9 NG0EE`A33M33K DI BIlNG90H')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1U1UDDAAHHFHH MUALLA`III NNGGEEWEEEE BBRUUTTA4ALL BANGGETT DDIIBBEEIYYYIOOHHHn')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group QW^1p1p NNGGEFSEWEEEE BB`RUUTTA4ALL BANGGETT DDIIBBEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1BB1OECIL DI GGANGBNK D`IHIIIBHIOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1U1UDY`DDEHH BASSSAHHH` BANGETT KK ITU SINII BURUUANNNN')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11O`OUHH INI DIA YYAANG VHIRAL CUSSSS BHI0000')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1S1Z`III ALEEAAA ANGEEEEE BB1HYYYYYTOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1S1S,IARAAA`N LANGSUNG PEER0MEEKAAANN DIB;1Y000HHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11CEE`EKKK DI PLHOPJIL AKU ADDA YANG LAGI ENHAK ENHAK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1O1O`UHHMEX PINKKKK FULL DDESAG BANGET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1A1A4KUU`UUU COOLLLMEEEEKKK BHYYYEIOOOOOOKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^11JIIILLBBB`OOOBBS OMMMMEEECGK DEBHHHHHIOIOOOOH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1AA1DDD`DHA YYYAAN9 NG0EE3E3M3E3K DI BIlNG90H')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1U1UU`D.DADAHHHH MULLAIII NNGEGEEEWEEEE BBRUUTTA4ALL BANGGETT DDIIBBEEIYYYIOOHHHn')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group QW^1p1`p NN`HGGEEDWEEEE BBRRRUUUTTA4AALL BANGGETT DDIIBBEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1BB01OO``CIL DI GGGGAANGBNK DI1HIIlIIBHIOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1U1UIDDD`DDEEEEEHH BASSAHHH BBANNGGETT KK ITU SINII BURUUANNNN')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1OO1OHHH `IN.NI DDIA YANG DVAHIRAL CUSSSSSSS BHI0000')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.bc group QW^1R12WWI`WOI A.NJRIT, NGHEWENYA BWARABWAR BGT DIBHIOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1M1ALLLE`EEMMR.MM IINNNI PPAAARTTYYY NGGAGGEEIWEEEEEE DEEBBBBBBIIOOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(300)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1N1NNGG`GEEEWEEEE BBBRUUTTA4ALL BANNAGGGETT DDIIBBEEEIIOOHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1A1DDH`A YAAN9G NG0EIE33M33K DI BIlANG90H')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1S1SSIIAAI`ARAAAN LANGSUNG PER0MEEAEKAAANN DIB;1Y000HHHKKkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1L1LISTINIIi`IERR KIAA OMEXKCG BAWBRBAWRR DBYOHGHHHFF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1O1OOUH`HMEX PINKKK FULL DESAAG BANNAGGEET DI BYOCHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1AQ1KU `ANGGHEKKKK PARAHHHHDI BYUIAOHHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1CC1H``OLLLMEE3KKKKKINN`NN BBBBHHHIIIYAYUUUUHHHUK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1`C1CH`AHO1LLLL MEEEKKKINNNN BHHHYIIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^113NHN-GAUEWE`EE BBRUTALLL BGTTT DI BIYOOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1`CH4OLLLLMEEFEKKKIA~NNNN BHIHHYIIIOUYHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1`10`MMA`4MMIII~I OOEMAMEEEXXCKK BBBHYIIIOOUKKIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1O7O.OHHHME.~EECXKKINANN MOMMMIIIIIKUI BHHHHIIIIOOOYOOOOK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1M4MAA4AMMIIII ~OOEM1MEEEXXCKK BBBHYIIIOOUKKIIII')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1F8FULL OSMECCCKSS ~DESAHHH DIYY BIYYOOOUHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1B42ATLEEE  OMEKKK VS ~BATLEEE COLY DI BIUHHHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^178UD4AHHHHHH D1MULAIIIII ~BURU4NNNNNN CEKKKKKK B1000KKKKKKCKKK1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1T12IEEEEMMEEEININN ~AKKKUUU SAINGGGEEEEKK DDDEEEBEEE1O')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1MEM312MMMMKS~ TEMBEM DIIBYIIOOU AK SAYANGGGF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1LIVF32EEE NGEUWEEE ~£UDAAHHH MULAIIII DI BIYOOOOU BURU JOINNNN1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1TIE32EEMMMEEEININN £AKKKUUU SAINGDGGEEEEKK DDDEEEBEEEOI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^1SOK109NN TM0 C`UANN ¢DIBYIOUHHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.bc group QW^1A441NA4K SMA NGEU33 ¢SAMA OM` DI BBHHEYOKKK')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(320)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
  except:
    print(f'{hijau} Gcast gagal.! {putih} gcast by : khairil')
    sleep(120)

sys.exit()
client.disconnect()
