from telethon import TelegramClient, sync, events
from telethon.tl.functions.messages import GetHistoryRequest, GetBotCallbackAnswerRequest
from telethon.tl.functions.channels import JoinChannelRequest
from telethon.errors import SessionPasswordNeededError
from telethon.errors import FloodWaitError
from time import sleep, time
from colorama import Fore,Style, init as color_ama
color_ama(autoreset=True)
import json, re, sys, os, random

banner = Style.BRIGHT+Fore.YELLOW +  """

   ____               _   
  / ___| ___ __ _ ___| |_ 
 | |  _ / __/ _` / __| __|
 | |_| | (_| (_| \__ \ |_ 
  \____|\___\__,_|___/\__|
                          
  Creator : MK KHAIRIL || Youtube : MK KHAIRIL
  Support : Cocentz404 || Youtube : Cocentz404"""

putih = Style.BRIGHT+Fore.WHITE
hijau = Style.BRIGHT+Fore.GREEN
merah = Style.BRIGHT+Fore.RED
kuning = Style.BRIGHT+Fore.YELLOW
reset = Fore.RESET
biru = Style.BRIGHT+Fore.BLUE


os.system('clear') 
print(banner)
print("\n")
print(f'{hijau}[+] Indonesia/English')
import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
#kecepatan mengetik
        time.sleep(random.random() * 0.2)
#ubah angka 0.1 sesuai keinginan kamu
#angka terkecil adalah yang paling cepat
#angka terbesar adalah yang paling lambat
mengetik("[+] Ini Adalah Program Ilegal\n[+] Semua Resiko Harap Ditanggung Pengguna..!!\n[+] This Is An Illegal Program\n[+] All Risks Borne by Users...!\n")
if not os.path.exists('session'):
    os.makedirs('session')
if len(sys.argv) < 2:
    print( Fore.RED + '\n\nUsage : python main.py +62' + Fore.RESET)
    sys.exit(1)
api_id = 1148490
api_hash = 'd82c81323285aeb9c2ba9ee420d8b009'
phone_number = sys.argv[1]
client = TelegramClient('session/' + phone_number, api_id, api_hash)
client.connect()
if not client.is_user_authorized():
    try:
        client.send_code_request(phone_number)
        me = client.sign_in(phone_number, input(Fore.WHITE + 'Enter Yout Code Code : '))
    except SessionPasswordNeededError:
        passw = input(Fore.RESET + 'Your 2fa Password : ')
        me = client.start(phone_number, passw)
saia = client.get_me()
print('[*]Account:',saia.first_name)
print('[*]Phone:',saia.phone,'\n')
channel_username = '@gcastod'
channel_entity = client.get_entity('@gcastod')
print('Memulai Bot Gcast..!')


while True:
  try:
    client.send_message(entity=channel_entity, message='.bc group Kammoe kebyiuuuu buruaaahn ada omegck??')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Callsx yukck')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Pdhal aku ngewee3 dibhiyiooo')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Baru bngun dah ang3eeee ajaa')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Siniii mami tmeniiniinn Croottttts nyya senggg')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Sepiiiiee nihhh pcccssesssess')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Ahhhhhrw enakk bngggetttss')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Mau dongg dikiriminn pap')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group sayyanggg anggeeeeeb mamii')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    
    client.send_message(entity=channel_entity, message='.bc group mau manja deh aku nya hwehehe')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)    
    client.send_message(entity=channel_entity, message='.bc group wiwikw')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)    
    client.send_message(entity=channel_entity, message='.bc group ohh disini ya sibuk ya hmmm')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group mami dsini mantau yaa,pstii coli semua')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group mandhii yukk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group aqkaquuuuu omexxxx dibyoooughh^')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group sini dong jilatinnnnnnn hwehehee')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group mami rate ya, ayokkk dongggd')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group paddaa oummeeeckkj diiibboioojhh ihhhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group chooliii pake balsem seruuu dhhiii biiooyooo0')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group -1 ayangggg nihh,yg hyper sex')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group FULL OSMECCCKSS DESAHHH DIYY BIYYOOOUHHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group ^JJJlllLLBBOBBSS CANTTllKKK NGGGGEEEWWWEEEE DBBBIIIllOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group ^mekiipinkyy lg di 33wvwee debheeiiyooo0')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Aqaquuuuu omexxxx dibyoooughhHI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group 00OOOOOIMMEEEECCKK DDDDDlllEEBBEEOOOOIKI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group NGNNGGGGEEEWEWWWIEEEEEII BANGGEETSSS BHHHlllIIIIOOOOYO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group ^FFFFULL OSMECCCKSS DESAHHH DIYY BIYYOOOUHHHHh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group AD^ADA C0UL0UKK C0UL0UK MEMEMEEKKK TEUMB€MMM BHEYOUKHHH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group AQAKKKHUUUU LAGHHIII OMMHHE3XGK DBHYEIIIOOOO0')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group JJParty omeccckk siang deebeohku')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group JIJJJlllLLBBOBBSS CANTTllKKK NGGGGEEEWWWEEEE DBBBIIIllOO')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Aaaakuuuu udahhhh ANGHEE bangtttt di byyuiiioooihh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Lllagi pd mainin lubang pipis di bihyoo')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group UDaaUUDYDDEHH BASSSAHHH BANGETT KK ITU SINII BURUUANNNN')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Mmmekkkikuu pinkk bngetttt diibiuoyoo')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group mnddii barenggan mmamihh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group crro00ttt dii mukaa ya')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Enakkkk bngetttssss lemessss ahhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group pen di ewee kmuuu beb')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group inpo yg suka jilatt dongg')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group ahhhhh beceekk bngettt')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group squirt brengg kmuu yukkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group gelii bngettt bnyk bulu nyaa')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group dbyoughhtr adaaaa yg onmeekcg bngett buruaann')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group SsSumpaaahhhhhhhhhhhh beceeeekkkk bbngggeeeettttttttt dbbbbyuuhhhhhuuuuuy')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group GangBangDhiBiyooo')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group BocillLiveeOumeeckkDiibiiooyookuuhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Omeeccxx^Enakkkk^Cuaca^Gini')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Party^Omekkcxxxxxx^Ada^Dibiiyyyyyoooouuuuuuhhhhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Dhiibiyoooookuuu addaaaa mmmmmeekkkk pinkkkk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Tmeeneninnn^Ommmmmeeecckkkkkkkxxxxx^DiBiyooooookkkkkkkuuuuuhhhhhhhy')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Omeccxkkkkkkk Sambbbillllll Mandddiiiiii DiiHiiiBiyooooooooouu')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Bagussss^Bngetttttt>^Mekkiiinyaaa')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Anaallll 3 jariii diibiiiyooyoooooooo')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group yukk crootttinn ke mukaaa akuu')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Enakkkkyaa akuu tmeniinnn crotttnya')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Uddhhh noontoonnnnn mekiii pinkkk pakeee mokarizo??')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Keeeenannakkkkann Crotttt di dlemm yaa ayanggg')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group ppeeeeekkkkknya^PinkkkBngetttdehhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group jgn manja deh mls aku nya hwehehe')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)    
    client.send_message(entity=channel_entity, message='.bc group wiwikw')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240) 
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group ohh disini ya, sibuk ya hmm,tmenin omeeckkkx')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group mami angheee nihh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group maandhii yukk')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group aaqkaquuuuu omexxxx dibyoooughh^')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group ssini dong hwehehee')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group rrate mami dongggd')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group paaddaa oummeeeckkj ihhhh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group choooliii pake balsem seruuu dhhiii biiooyooo0')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group -1 ayangggg nihh')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group QW^1Qu1FFULL OSMECSCCKSS DESAHHH DIYY BIYYOOOUHH1HH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1BATLEEE  OMEKCKK VS BATLEEE COLY DI BIUHHHHHHH1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group QW^11QWUD4AHHHHHH D1MUULAIIIII BURU4NNNNNN CEKKKKKK B1000KKKKKKKCKKK1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1TIEEEEMMEEEININNN AKKKUUU SAINGGGEEEEKK DDDEEEBEEE11O')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group QW^1QW1MEM31MMMLMKS TEMBEM DIIBYIIOOU AK SAYANGGGGF')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group HEii 1QWL1IVFEEE NNGEUWEEE UDAAHHH MULAIIII DI BIYO0OOOU BURU JOINNNN1')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group Sayangg 11QWTIEEEMMMMEEEININN AKKKUUU SAINGDGGE3EEEKK DDDEEEBEEEOI')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.bc group BURuua 1QW1SOKK1NN TM0 C`UANN DIBYIOUHHH1HH')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(240)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Kammmoe kebyiuuuu buruaaahn ada omegck??')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Callsx yukck')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Pdhaal aku ngewee3 dibhiyiooo')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group BBaru bngun dah ang3eeee ajaa')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group SSiiniii mami tmeniiniinn Croottttts nyya senggg')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Seepiiiiiee nihhh pcccssesssess')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group Ahhwhhhrw eneakk bngggetttss')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
    client.send_message(entity=channel_entity, message='.bc group Moau doungg dikiriminn pap')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.bc group sayyaanggg anggeeeeeb mamii')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(200)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(8)
    client.send_message(entity=channel_entity, message='.limit')
    print(f'{hijau} Gcast berhasil.! {putih}gcast by : khairil')
    sleep(5)
  except:
    print(f'{hijau} Gcast gagal.! {putih} gcast by : khairil')
    sleep(120)

sys.exit()
client.disconnect()
